#!/bin/bash

if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

if command -v tmux &> /dev/null && [ -z "$TMUX" ] && [ -n "$SSH_TTY" ] && [[ $- =~ i ]]; then
        tmux new -A -s default
fi
