#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

HISTCONTROL=ignoreboth
HISTIGNORE='ls:history:cd'
shopt -s histappend

shopt -s extglob
shopt -s failglob

eval $(dircolors ~/.dir_colors)

alias ls='ls --color=auto'

function mk { mkdir -p "$1" && cd "$1"; }
