#!/bin/bash

SCRIPT_DIR="$(readlink -f ${BASH_SOURCE[0]})"
BASEDIR="$(cd $(dirname "$SCRIPT_DIR")/.. && pwd)"

EDITOR="vim"
PATH="$PATH:$BASEDIR/bin"

if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi
