#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?* ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

VBoxClient --clipboard --seamless --display --checkhostversion

export VDPAU_NVIDIA_NO_OVERLAY=1 # nvidia flash fix
setxkbmap -option 'compose:ralt'
setxkbmap -option 'compose:menu'

#if xrandr | grep -q VGA; then
#    xrandr --output VGA-0 --right-of LVDS-0
#fi
#
#xflux -l 48.252644 -g 16.399960
#exec i3 -V >> ~/i3log-$(date +'%F-%k-%M-%S') 2>&1
