#!/bin/bash

userresources=$HOME/.Xresources

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?* ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# in case we run in a VM
VBoxClient-all

export VDPAU_NVIDIA_NO_OVERLAY=1 # nvidia flash fix
setxkbmap -option 'compose:ralt'
setxkbmap -option 'compose:menu'

exec i3 -c $HOME/.i3config
