let s:path = fnamemodify(resolve(expand('<sfile>:p')), ':h')
execute 'set packpath+=' . s:path

" ===============
" general options
" ===============
filetype plugin indent on
syntax enable
set hidden
set autoread
set history=1000
set autochdir
set undofile
set undodir=~/.vim/undo
set nowritebackup
set nobackup
set noswapfile
set encoding=utf-8
set termencoding=utf-8
set fileencodings=ucs-bom,utf-8,default,shift-jis,latin1
set shellslash
set foldmethod=marker

" ===============
" editing options
" ===============
set expandtab
set shiftwidth=4
set backspace=indent,eol,start
set cinoptions=(s,m1,h0
set formatoptions-=o
set nrformats-=octal
set virtualedit=block
set nojoinspaces

if v:version > 703 || v:version == 703 && has("patch541")
    set formatoptions+=j
endif

" ==========
" ui options
" ==========
set ruler
set wildmenu
set wildmode=longest:full
set wildignore=*.pyc,*.jpg,*.gif,*.png,*.exe
set hlsearch
set incsearch
set laststatus=2
set scrolloff=1
set sidescrolloff=5
set display+=lastline
set list
set listchars=tab:▸\ ,trail:←,nbsp:¬
set cursorline
set nonumber
set norelativenumber
set showcmd
set ttyfast
set mouse=
"set lazyredraw

set background=dark
set guioptions-=m
set guioptions-=T
set guioptions-=t

if has('win32')
    set guifont=DejaVu_Sans_Mono:h11,Lucida_Console:h11
else
    set guifont=DejaVu\ Sans\ Mono\ 11
end

silent! colorscheme bubblegum-256-dark

" vim hardcodes background color erase even if the terminfo file does
" not contain bce (not to mention that libvte based terminals
" incorrectly contain bce in their terminfo files). This causes
" incorrect background rendering when using a color theme with a
" background color.
let &t_ut=''

" =======
" plugins
" =======
let loaded_matchparen = 1 " don't load matchparen plugin

" if vim is recent enough, load built in package matchit
if has('syntax') && has('eval')
    packadd matchit
endif

let g:rainbow_active = 1

" enable :Man support
runtime! ftplugin/man.vim

" ========
" mappings
" ========
"
" for windows only:
silent! vunmap <C-X>

let mapleader=" "

nnoremap <Leader><Leader> :nohlsearch<CR>
nnoremap <leader><tab> <C-^>

" vim-fzf mappings
" Mapping selecting mappings
nmap <leader>m <plug>(fzf-maps-n)
xmap <leader>m <plug>(fzf-maps-x)
omap <leader>m <plug>(fzf-maps-o)

" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
"imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-l> <plug>(fzf-complete-line)
inoremap <expr> <c-x><c-f> fzf#vim#complete("fdfind <Bar> xargs realpath --relative-to " . expand("%:h"))

nnoremap <leader>o :Files<cr>
nnoremap <leader>g :GFiles<cr>
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>s :GFiles?<cr>
nnoremap <leader>l :Lines<cr>

" visual-multi
let g:VM_leader = ','

" airline
let g:airline_theme='bubblegum'
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_section_z=''
au User AirlineAfterInit  :let g:airline_section_z = airline#section#create(['windowswap', 'obsession', '%3p%% %l', 'maxlinenr', ' :%3v'])

" fern
nnoremap <leader>f <Plug>(fern-action-project-top:reveal)
